### ISSUE TITLE
Number of bits not preserved in `tk_to_qiskit` conversion with `RangePredicate`

### ISSUE THREAD

**Issue by CalMacCQ** [CQCL/pytket-qiskit#410]
Whilst looking into https://github.com/CQCL/pytket-qiskit/issues/375 I found that the number of bits was not preserved in the tk_to_qiskit conversion. I think this may well be the cause of the `KeyError` issue.

```python
from pytket import Circuit, OpType
from pytket.circuit.logic_exp import reg_eq
from pytket.extensions.qiskit import tk_to_qiskit


main_circ = Circuit(2, 2, "main_circ")

creg_0 = main_circ.add_c_register("creg_0", 2)

main_circ.add_gate(OpType.CH,[0, 1], condition = reg_eq(creg_0, 3))

main_circ.measure_all()
print(main_circ.n_bits) # gives 5
```
![Image](https://github.com/user-attachments/assets/aef48aff-6c19-4114-805d-051f75ed4292)

But if I convert to a qiskit `QuantumCircuit`...

```python
qc = tk_to_qiskit(main_circ)
print(qc.num_clbits) # gives 4
```

We only get 4 bits in the converted qiskit circuit. it seems the `tk_SCRATCH_BIT[0]` bit is lost in the conversion.

**Comment by yao-cqc** [comment]
I think this is expected. In pytket, a scratch bit is required to store the evaluation of a range predicate, for example, `if c == 2 tk_scratch_bit[0] = 1`, and then condition a gate on that scratch bit, i.e., `if tk_scratch_bit[0]==1 H(1)`. When converting such a conditional gate to qiskit, we combine these two instructions into one and remove the separate evaluation, resulting in ` if c == 2 H(1)`. Since `tk_scratch_bit` is no longer used, we don't add it to the qiskit circuit.

```python
qc[0].condition
```
prints
```
(ClassicalRegister(2, 'creg_0'), 2)
```
suggests that the CH gate has the correct condition

**Comment by CalMacCQ** [comment]
Closing as I think this is expected behaviour.
