### ISSUE TITLE
`AerBackend().backend_info.gate_set` is missing some gates

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket-qiskit#75]
There are some gates that are (correctly) accepted by the backend's `GateSetPredicate`, but are missing from its `backend_info`. Namely: `Barrier`, `RangePredicate`, `Measure`, `Reset`, and `Unitary1qBox`.

**Comment by trvto** [comment]
Is it in general the case that the `GateSetPredicate` and `backend_info.gate_set` should contain the same gates? If so, the code, as it is, is very confusing

**Comment by cqc-alec** [comment]
I can't think of a reason why it would not be the case. Some of this code dates back a long way (certainly since before there were any predicates), so feel free to make less confusing if you can!

**Comment by trvto** [comment]
Should the `rebase_pass` contain these gates as well?

**Comment by cqc-alec** [comment]
> Should the `rebase_pass` contain these gates as well?

Ideally yes, though `Measure` and `Reset` are automatically added I think.

**Comment by trvto** [comment]
Here (https://github.com/CQCL/pytket-qiskit/blob/develop/pytket/extensions/qiskit/backends/aer.py#L91) is a list of required gates. Is there a reason these gates are required?

I'm asking because, after some refactoring, this [line](https://github.com/CQCL/pytket-qiskit/blob/develop/tests/backend_test.py#L898) of test code fails, because `AerBackend(simulation_method="stabilizer")` doesn't contain the "required" `u1`-`u3` gates. This wasn't failing before because the required gate check was happening before setting the `simulation_method` to "stabilizer", so that the gates available from `simulation_method=automatic` were being used for the check, which seems like a bug to me. But now the "required" gates check fails so I'm not sure what to do...

**Comment by cqc-alec** [comment]
> Here (https://github.com/CQCL/pytket-qiskit/blob/develop/pytket/extensions/qiskit/backends/aer.py#L91) is a list of required gates. Is there a reason these gates are required?

I don't know why those particular gates should be required -- indeed for stabilizer backends the u1-u3 shouldn't be required. Does anything break if we remove this check?

**Comment by trvto** [comment]
Hmmm, other tests don't break but now in [this](https://github.com/CQCL/pytket-qiskit/blob/develop/tests/backend_test.py#L914) line, instead of getting an `AttributeError` from within qiskit when trying to retrieve the result, we now get a `CircuitNotValidError` when validating the circuit:
```
pytket.backends.backend_exceptions.CircuitNotValidError: Circuit with index 0 in submitted does not satisfy GateSetPredicate
```

Which actually seems much better...
